"""product table

Revision ID: 618d0cb87062
Revises: f31c1239ab75
Create Date: 2022-05-24 11:15:15.567113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618d0cb87062'
down_revision = 'f31c1239ab75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
